### ISSUE TITLE
BambooStorage.Internal should provide API for transactions

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/bamboo-storage#41]
Currently, we need several methods:

```java
areTransactionsSupported()
beginTransaction()
setTransactionSuccessful()
endTransaction()
```

Just like pure `SQLiteDatabase`

Will be useful for #40 `put(collection)` and `delete(collection)` operations

**Comment by artem-zinnatullin** [comment]
@nikitin-da I'll take it, I have several hours to do it

**Comment by nikitin-da** [comment]
ok
