### ISSUE TITLE
execSql support

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/bamboo-storage#63]
I think it should be part of `BambooStorage`, we can provide `blocking` and `Observable` variants.

`bambooStorage().execSql(SQLQuery).prepare()`
`Execute a single SQL statement that is NOT a SELECT/INSERT/UPDATE/DELETE.`

And `SQLQuery` + `SQLQueryBuilder`, which will be same as `RawQuery`

@nikitin-da any comments?

**Comment by nikitin-da** [comment]
What do you mean by "NOT a SELECT/INSERT/UPDATE/DELETE" ?

**Comment by artem-zinnatullin** [comment]
http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#execSQL(java.lang.String, java.lang.Object[])

For example: `ALTER, DROP` and so on

**Comment by nikitin-da** [comment]
Ok, let's do it.

**Comment by artem-zinnatullin** [comment]
Cool

Next question: should Query extend RawQuery? And should be SQLQuery be a RawQuery?

**Comment by nikitin-da** [comment]
"should Query extend RawQuery?" I think yes, it will be slightly more holistic, imho.
"And should be SQLQuery be a RawQuery?" I guess it is the same, isn't it?

**Comment by artem-zinnatullin** [comment]
Hm, we should think about it very carefully, because we can have problems with inheritance in future.

We have list of entities:
`RawQuery: sql, args`
`Query: table, columns, selection, args, groupBy, having, orderBy, limit`
`InsertQuery: table, nullColumnHack`
`UpdateQuery: table, where, args`
`DeleteQuery: table, where, args`

If we will design them using inheritance, we will have problems like: converting `Query` to `RawQuery` and so on, I think we can use `RawQuery` for `execSql()` and don't use inheritance of queries for release 2.0.0 to avoid potential problems

**Comment by artem-zinnatullin** [comment]
Or we can use next approach:

We can have ONLY `RawQuery` and builders for all types of queries which will build `RawQuery` instance

**Comment by artem-zinnatullin** [comment]
But using only `RawQuery` allows to do incorrect queries, for example: build `insertQuery` and use it for `bambooStorage.delete()` and similar.. We can avoid them in compile time by correct usage of types

**Comment by nikitin-da** [comment]
Maybe Query, InsertQuery, UpdateQuery and DeleteQuery will extend abstract class with common field "table", and ok, RawQuery will be POJO and use for execSql?
I don't quite understand what is SQLQuery. Does it differ from the RawQuery?

**Comment by artem-zinnatullin** [comment]
Forget about `SQLQuery`, it will be `RawQuery` :)

Base class with `table` field is good idea for `Query`, `InsertQuery`, `UpdateQuery` and `DeleteQuery` , but we will have to do inheritance:
`Query`, `InsertQuery`, `UpdateQuery` and `DeleteQuery` can extend `RawQuery`, but it will require some extra amount of work from us to manually convert `Query`, `InsertQuery`, `UpdateQuery` and `DeleteQuery` to `RawQuery`, which is not so easy and can be tricky/buggy.

What advantages will we get via inheritance?

**Comment by nikitin-da** [comment]
I don't see any advantage, except a bit more integrity. 
Yes, converting will be complicated. 
I see tree ways: 
* custom generating raw sql string 
* common method will take helper as argument, and do, what he want %)
* or retrieve concrete class.
There are no any common state or behavior, so I guess inheritance is not needed.
Method `withQuery`, as we have already decided will be use overload, so different classes is better choice.

**Comment by artem-zinnatullin** [comment]
3rd approach is the best for me :+1: 

Also, if we will really need it, we will be able to add inheritance later without breaking compatibility :)

**Comment by nikitin-da** [comment]
Consensus
