### ISSUE TITLE
Seems that RxJava will be required dependency :(

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/bamboo-storage#76]
Unfortunately, with features #74 and #75 it will be easier to include RxJava as required dependency than creating wrappers for hiding access to RxJava classes if user don't use it.

But, I think it's okay for `BambooStorage` v2.0.0

**Comment by nikitin-da** [comment]
Are there any capabilities to remove it in future?

**Comment by artem-zinnatullin** [comment]
Yes! Just extra work for us

пт, 6 марта 2015, 20:45, Dmitrii Nikitin <notifications@github.com>:
