### ISSUE TITLE
Rename PreparedOperation.createObservable()

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/bamboo-storage#77]
It should clearly show intent: observable that will be created will listen only 1 result

See #74 

@nikitin-da what do you think?

**Comment by nikitin-da** [comment]
Hm, `createObservableStream` for 1 result? Is not quite clear for me  :( May be `createResultObservable`?

**Comment by artem-zinnatullin** [comment]
Not required :)
