### ISSUE TITLE
Make BambooStorage and BambooStorage.Internal abstract classes instead of interfaces

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/bamboo-storage#90]
It will allow us to add new functionality which will use already existent methods without breaking API for those, who decided to implement their own versions of `BambooStorage`

@nikitin-da your opinion?

**Comment by nikitin-da** [comment]
About what functionality do you say?

**Comment by artem-zinnatullin** [comment]
For example #88, with abstract class it can be just like this:

```java

@NonNull public Observable<String> observeChangesInTable(@NonNull String table) {
  return observeChangesInTables(Collections.singleton(table)); // reusing existent method
}
```

**Comment by nikitin-da** [comment]
Ok, let it be.

**Comment by artem-zinnatullin** [comment]
:smile:
