### ISSUE TITLE
No result when put object again

### ISSUE THREAD

**Issue by nikitin-da** [pushtorefresh/bamboo-storage#97]
What do you think, is it expected for default put resolver, that when you: 
1) put object
2) delete it
3) and put again the same object (with not null internal id)

As a result, there is no any changes in storage after second put.
May be we can check result of update in second case, and try use insert?

**Comment by artem-zinnatullin** [comment]
Damn, great use case. I'll think about it and comment

пт, 13 марта 2015, 8:10, Dmitrii Nikitin <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
I see two things:

1. Put object can set inserted id, and we can add delete resolver which will just remove id from object.
2. We can add check to default put resolver and make insert if update returned 0

Also, we can add resolvers for all operations, put, get, delete with default implementations to allow users customize behavior of the operation, what do you think about it?

**Comment by nikitin-da** [comment]
I just think only about second variant. 
But resolver for all operations, that by default will resolve this issue and will be hide from user in common case, it sounds flexibly.

**Comment by artem-zinnatullin** [comment]
So, I'll create an issue for resolvers! Better API for everybody
